### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by probablypablito**
You can use an environment variable called "ids" and set it to multiple ids separated by spaces

### CODE REVIEW

**Comment by probablypablito** [comment]
Here's a public version of it too: https://hub.docker.com/r/probablypablito/ow-league-tokens

**Comment by Juice805** [comment]
Github can create and host docker images with each release: [Docs](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages). This would probably be a great PR to a adopt it

**Comment by Nakda** [comment]
@probablypablito I built your source for arm64 successfully, but I did change the base image to `python:3.10.7-slim` to trim down its size (went from 900MB to 150MB). Thank you for providing a docker support!

**Comment by probablypablito** [comment]
thanks! I learned about buildx now and other stuff, I can update the PR if you want and build for other platforms.

I'll also try to upload to GitHub instead of docker

**Comment by probablypablito** [comment]
I updated the PR to use python-slim and also updated the Docker hub repo to use multi-arch and the slim base. 

Publishing to GitHub seemed kinda confusing, and I also don't want to deal with changing registries

**Comment by probablypablito** [comment]
eh it'll work either way

**Pull request merged**
